version: "2"

linters:
  enable:
    # Default linters
    - errcheck      # Checks for unchecked errors
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Advanced Go linter
    - unused        # Checks for unused constants, variables, functions and types
    # Additional linters
    - goconst       # Finds repeated strings that could be constants
    - gocyclo       # Checks cyclomatic complexity
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable linter (golint replacement)
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters

run:
  timeout: 5m
