name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test -v ./...

    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "${{ github.ref_name }}" \
          --notes "See [CHANGELOG.md](https://github.com/jecoms/regextra/blob/main/CHANGELOG.md) for details."
      env:
        GH_TOKEN: ${{ github.token }}
